services:
  - type: web
    plan: free
    name: d0st
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    repo: https://github.com/Un-0wn/X-URL-Uploader.git
    branch: master
    envVars:
      # - key: token
      #   sync: false
      # - key: APP_ID 
      #   sync: false
      # - key: ApiHash
      #   sync: false
      # - key: Auth
      #   sync: false
      # - key: BOT_USERNAME
      #   sync: false
      # - key: WEBHOOK
      - key: PORT
        value: 8443
      # - key: DEF_THUMB_NAIL_VID_S
      #   sync: false
      # - key: UPDATES_CHANNEL
      #   sync: false
      # - key: LOG_CHANNEL
      #   sync: false    
    autoDeploy: false